* progress

  25/342 2.2 resource

* chapter 01
** notes
*** 100 faster 
    cool, IBM 704 and you guys wanna build a new computer 100 faster
    than it? If I were one of the people working on that project, I
    would probaly say impossible. What a brave heart.
*** you can do it just a mater of time
    #+BEGIN_QUOTE
    In practical, however, any general-purpose computer can do any
    programmable problem, given enough time.
    #+END_QUOTE
*** I had a dream
    to build my computer to just run my emacs to do my daily jobs. Just
    like what I do right now.
** questions
** a-ha
* chapter 23
  Wow, so cool to use ~get~ command
  #+BEGIN_SRC 
$ ftp ftp.gnu.org
User (ftp.gnu.org:(none)): anonymous
cd
Remote directory ls
Failed to change directory.
ls
ls
CRYPTO.README
MISSING-FILES
MISSING-FILES.README
README
before-2003-08-01.md5sums.asc
find.txt.gz
gnu
gnu+linux-distros
ls-lrRt.txt.gz
mirrors
non-gnu
old-gnu
pub
savannah
third-party
tmp
video
welcome.msg
CRYPTO.README
MISSING-FILES
MISSING-FILES.README
README
before-2003-08-01.md5sums.asc
find.txt.gz
gnu
gnu+linux-distros
ls-lrRt.txt.gz
mirrors
non-gnu
old-gnu
pub
savannah
third-party
tmp
video
welcome.msg
cd gnu/diction
ls
diction-0.7.tar.gz
diction-1.02.tar.gz
diction-1.11.tar.gz
diction-1.11.tar.gz.sig
ls -al
drwxrwxr-x    2 0        3003         4096 Sep 17  2007 .
drwxrwxr-x  318 0        3003        12288 Jan 25 14:12 ..
-rw-r--r--    1 3003     65534       68940 Aug 28  1998 diction-0.7.tar.gz
-rw-r--r--    1 3003     65534       90957 Mar 04  2002 diction-1.02.tar.gz
-rw-r--r--    1 3003     65534      141062 Sep 17  2007 diction-1.11.tar.gz
-rw-r--r--    1 3003     65534         189 Sep 17  2007 diction-1.11.tar.gz.sig
get diction-1.11.tar.gz
bye
  #+END_SRC

  Unfortunately, I got this:
#+BEGIN_SRC sh
$ ./configure
checking build system type... ./config.guess: unable to guess system type
configure: error: cannot guess build type; you must specify one
#+END_SRC

I later follow the instruction of this book on a linux machine without
any issue. But, this book did not explain too much info on how
makefile works. So, I need do some further study.
** add-on reading
   [[http://www.cs.colby.edu/maxwell/courses/tutorials/maketutor/][this is good starting point]].
*** GNU Manual: An Introduction to Makefiles
    The goal of reading the manual to answer a question by [[https://www.cfd-online.com/Forums/openfoam-programming-development/196114-why-wmake-not-listen-me.html][myself]].
**** 2.1 What a Rule Looks Like
     Some people like space, but why the creator of make prefre tab?
**** 2.2 A Simple Makefile
     - what is cc?
     - what is object file?
