* Motivation

  Not sure how I got this book. Just find it on my desktop today. And
  I read some paragraph at the begining of this book.

  I am fascinating by the following sentence:

  #+BEGIN_QUOTE
  Freedom is the power to decide what your computer does, and the only
  way to have this freedom is to know what your computer is doing. 
  #+END_QUOTE

  This is something inline with someting deep in my mind. I am very
  comfortable with play with computers via command line, but I want to
  know more. Especially, I want to answer a question that initialize
  this journey:

  #+BEGIN_QUOTE
  how to damage my computer using your code?
  #+END_QUOTE

* Progress
  
  90/544 of course: Erector Set

* Notes
** Chapter 1

   - ~Alt + F1 to F7~: switch curtain
   - Stephen R. Bourne: an mathmatician build the Bourne Shell
   - symbolic links could solve the naming a file that changes its
     name
   - create a new file ~> newfile~
   - joke: warning users that the system's /dev/null is already 98%
   - create a easy file with easy info
     #+BEGIN_SRC 
     $ cat > dummy.tex
     This is your input.
     #+END_SRC
     Then, ~Control + D~.
   - ~>~ can silently overwrite stuff, becareful.
   - uniq: delete uncessary lines
   - grep: -i ignore case
** Chapter 7
   - Brace Expansion: never use it before (cannot remember well)
     
     So powerful!

     #+BEGIN_SRC sh
     $ mkdir {2011..2019}-{01..12}
     #+END_SRC
     
     Then I got a lots of subfolder!

   - shell expansion:

     #+BEGIN_QUOTE
     Without a proper understanding of expansion, the shell will
     always be a source of mystery and confusion, and much of its potential power wasted.
     #+END_QUOTE
     
     I will stop at this point and do something to make my hands duty.
* Questions
* Exercises
