* Motivation

  Not sure how I got this book. Just find it on my desktop today. And
  I read some paragraph at the begining of this book.

  I am fascinating by the following sentence:

  #+BEGIN_QUOTE
  Freedom is the power to decide what your computer does, and the only
  way to have this freedom is to know what your computer is doing. 
  #+END_QUOTE

  This is something inline with someting deep in my mind. I am very
  comfortable with play with computers via command line, but I want to
  know more. Especially, I want to answer a question that initialize
  this journey:

  #+BEGIN_QUOTE
  how to damage my computer using your code?
  #+END_QUOTE

* Progress
  
  84/544 The superuser

* Notes
** Chapter 1

   
   - ~Alt + F1 to F7~: switch curtain
   - Stephen R. Bourne: an mathmatician build the Bourne Shell
   - symbolic links could solve the naming a file that changes its
     name
   - create a new file ~> newfile~
   - joke: warning users that the system's /dev/null is already 98%
   - create a easy file with easy info
     #+BEGIN_SRC 
     $ cat > dummy.tex
     This is your input.
     #+END_SRC
     Then, ~Control + D~.
     
* Questions
* Exercises
